//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.261
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebControllers.AccWsRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccWsRef.AccountWebServiceSoap")]
    public interface AccountWebServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 res 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetResult", ReplyAction="*")]
        WebControllers.AccWsRef.GetResultResponse GetResult(WebControllers.AccWsRef.GetResultRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResult", Namespace="http://tempuri.org/", Order=0)]
        public WebControllers.AccWsRef.GetResultRequestBody Body;
        
        public GetResultRequest() {
        }
        
        public GetResultRequest(WebControllers.AccWsRef.GetResultRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetResultRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string res;
        
        public GetResultRequestBody() {
        }
        
        public GetResultRequestBody(string res) {
            this.res = res;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResultResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebControllers.AccWsRef.GetResultResponseBody Body;
        
        public GetResultResponse() {
        }
        
        public GetResultResponse(WebControllers.AccWsRef.GetResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetResultResult;
        
        public GetResultResponseBody() {
        }
        
        public GetResultResponseBody(string GetResultResult) {
            this.GetResultResult = GetResultResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccountWebServiceSoapChannel : WebControllers.AccWsRef.AccountWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountWebServiceSoapClient : System.ServiceModel.ClientBase<WebControllers.AccWsRef.AccountWebServiceSoap>, WebControllers.AccWsRef.AccountWebServiceSoap {
        
        public AccountWebServiceSoapClient() {
        }
        
        public AccountWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebControllers.AccWsRef.GetResultResponse WebControllers.AccWsRef.AccountWebServiceSoap.GetResult(WebControllers.AccWsRef.GetResultRequest request) {
            return base.Channel.GetResult(request);
        }
        
        public string GetResult(string res) {
            WebControllers.AccWsRef.GetResultRequest inValue = new WebControllers.AccWsRef.GetResultRequest();
            inValue.Body = new WebControllers.AccWsRef.GetResultRequestBody();
            inValue.Body.res = res;
            WebControllers.AccWsRef.GetResultResponse retVal = ((WebControllers.AccWsRef.AccountWebServiceSoap)(this)).GetResult(inValue);
            return retVal.Body.GetResultResult;
        }
    }
}
